# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a sample input configuration file for Shaka Streamer for webcam input.

# List of inputs.
inputs:
    # The type of input.
  - input_type: webcam
    # Name of the input device.  On Linux, this is a device node path.
    # On macOS, this is a device name, typically "default".
    # On Windows, this is the name of the directshow capture source, which
    # differs based on the hardware.  On a laptop this will typically
    # be "video=Integrated Camera".
    name: /dev/video0
    # The media type.
    media_type: video
